import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import membresRouter from "./membres";
import cotisationsRouter from "./cotisations";
import assistancesRouter from "./assistances";
import dashboardRouter from "./dashboard";
import annoncesRouter from "./annonces";
import parametresRouter from "./parametres";
import pdfRouter from "./pdf";
import importMembresRouter from "./import-membres";
import importCotisationsRouter from "./import-cotisations";
import pretsRouter from "./prets";
import departsRouter from "./departs";
import projetsRouter from "./projets";
import assembleesRouter from "./assemblees";
import electionsRouter from "./elections";
import bureauRouter from "./bureau";
import commissariatRouter from "./commissariat";
import comptabiliteRouter from "./comptabilite";
import sportsRouter from "./sports";
import documentsRouter from "./documents";
import communicationsRouter from "./communications";
import retraiteComplementaireRouter from "./retraite-complementaire";
import effectifsRouter from "./effectifs";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(membresRouter);
router.use(cotisationsRouter);
router.use(assistancesRouter);
router.use(dashboardRouter);
router.use(annoncesRouter);
router.use(parametresRouter);
router.use(pdfRouter);
router.use(importMembresRouter);
router.use(importCotisationsRouter);
router.use(pretsRouter);
router.use(departsRouter);
router.use(projetsRouter);
router.use(assembleesRouter);
router.use(electionsRouter);
router.use(bureauRouter);
router.use(commissariatRouter);
router.use(comptabiliteRouter);
router.use(sportsRouter);
router.use(documentsRouter);
router.use(communicationsRouter);
router.use(retraiteComplementaireRouter);
router.use(effectifsRouter);

export default router;
